const HOUR = 60 * 60 * 1000;

module.exports = Object.freeze({
  REALTIME_TREND_LIMIT: 20,
  REALTIME_REFRESH_MS: HOUR,
  TRENDING_PRODUCT_REFRESH_MS: 4 * HOUR,
  TRENDING_PRODUCT_MIN: 20,
  TRENDING_PRODUCT_MAX: 30,
  PRODUCT_CANDIDATE_LIMIT: 6,
  DEFAULT_SELECTED_PRODUCTS_PER_TREND: 2,
  TOP_TREND_COUNT: 3,
  TOP_TREND_SELECTED_PRODUCTS: 4,
  ROLLING_INTERVAL_MS: 2500,
  NAVER_PRODUCT_TARGET: 2,
  MIN_PRODUCT_SCORE: 28,
  MAX_TRENDS_PER_CATEGORY: 4,
  MAX_TRENDING_PRODUCTS_PER_CATEGORY: 8,
  HOT_SCORE: Object.freeze({
    rankMax: 58,
    newEntry: 14,
    risePerRank: 2.2,
    riseMax: 22,
    stable: 2,
    fallPerRank: 0.7,
    fallMax: 8,
    specificityMax: 16,
    brand: 12,
    model: 10,
    season: 12,
    event: 8,
    generic: 30,
    broadCategory: 18,
    service: 100,
  }),
  PRODUCT_SCORE: Object.freeze({
    base: 8,
    fullKeyword: 48,
    tokenCoverage: 34,
    allTokens: 10,
    brandModel: 12,
    mainProduct: 14,
    accessory: 48,
    badTitle: 100,
    shortTitle: 8,
    image: 5,
    searchOrderMax: 8,
  }),
});
